"""empty message

Revision ID: aafe203e05c5
Revises: 4e235d14ab3d
Create Date: 2022-04-04 17:17:25.933578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aafe203e05c5'
down_revision = '4e235d14ab3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('usertype', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'usertype')
    # ### end Alembic commands ###
